package hoavd.test.manage.employee.common.constants;

public interface ResponseMessageConstants {
  String ERR_SYSTEM = "MSG_ERROR_SYSTEM";
  String USERNAME_ALREADY_EXIST = "MSG_USERNAME_ALREADY_EXIST";
  String INFORMATION_INVALID = "MSG_INFORMATION_INVALID";
  String EMPLOYEE_DOES_NOT_EXIST = "MSG_EMPLOYEE_DOES_NOT_EXIST";
  String CREATE_EMPLOYEE_SUCCESS = "MSG_CREATE_EMPLOYEE_SUCCESS";
  String UPDATE_EMPLOYEE_SUCCESS = "MSG_UPDATE_EMPLOYEE_SUCCESS";
  String DELETE_EMPLOYEE_SUCCESS = "MSG_DELETE_EMPLOYEE_SUCCESS";

  //LOGIN
  String LOGIN_SUCCESS = "MSG_LOGIN_SUCCESS";
  String TOKEN_EXPIRED = "MSG_TOKEN_EXPIRED";
  String TOKEN_INVALID = "MSG_TOKEN_INVALID";
  String LOGIN_REFRESH_EXCEPTION = "MSG_LOGIN_REFRESH_EXCEPTION";
  String AUTHENTICATION_EXCEPTION = "MSG_AUTHENTICATION_EXCEPTION";
}
